Hw8
Kilim4ik/goiteens.homework pull request #36
Opened 2024-03-30 22:43 UTC by Kilim4ik

2024-04-09 14:37 UTC, marianaD4 requested changes

2024-04-09 14:37 UTC, marianaD4 commented on third semester/hw8/main.js
> +// console.log(string);
у результаті на початку буде ","
треба покращити рішення

2024-04-09 14:37 UTC, marianaD4 commented on third semester/hw8/main.js
> +// string = friends.join();
а де роздільник?

2024-04-23 13:49 UTC, marianaD4 requested changes

2024-04-23 13:49 UTC, marianaD4 commented on third semester/hw8/main.js
> +console.log(string);
потестував чи не буде коми спочатку?)

2024-04-23 15:51 UTC, Kilim4ik commented on third semester/hw8/main.js
> +console.log(string);
+

2024-06-10 14:19 UTC, marianaD4 approved these changes

2024-07-07 07:32 UTC, merged