Hw9
Kilim4ik/goiteens.homework pull request #37
Opened 2024-04-11 15:34 UTC by Kilim4ik

2024-04-23 13:43 UTC, marianaD4 requested changes

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +};
не той цикл
використовуємо for з лічильником

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +//! calculateEngravingPrice(prompt("...").split(" "), pricePerWord);
уважно message - рядок по завданню
тому split треба у функцію перенести

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +//! findLongestWord(prompt("...").split(" "));
split у функцію

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +let theLongestWord = "";
це локальна змінна функції - не потрібно виносити у глобальну область видимості

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +  console.log(theLongestWord);
по завданню потрібно повернути найдовше слово

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +  alert(`Кінцева вартість ${priceOfRing}`);
потрібно повернути price

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +// !formatString(prompt().split(""));
split всередину функції

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +//     console.log(`${message}...`);
не виводить, а ПОВЕРТАЄ )

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +//   console.log(`${message}...`);
як варіант може бути, але складно читати
краще 2 варіант
але за ініціативність +

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +//! checkForSpam(prompt().toLocaleLowerCase().split(" "));
split

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +  }
return не console.log
уважно читаємо завдання

2024-04-23 13:43 UTC, marianaD4 commented on third semester/hw9/main.js
> +  alert(`Загальна сума чисел дорівнює ${total}`);
повертаємо, а потім виводимо

2024-04-23 15:46 UTC, Kilim4ik commented on third semester/hw9/main.js
> +  for (let word of message) {
+

2024-04-26 21:01 UTC, marianaD4 requested changes

2024-04-26 21:01 UTC, marianaD4 commented on third semester/hw9/main.js
> +      break;
не потрібно `break` return припиняє виконання функції і циклу також

2024-05-07 14:19 UTC, marianaD4 approved these changes

2024-05-07 14:19 UTC, marianaD4 commented on third semester/hw9/main.js
>    }
можна використати скорочений синтаксис `return arrayFromMessage[i] === "spam" || arrayFromMessage[i] === "sale"`

2024-06-19 12:18 UTC, merged