Hw11
Kilim4ik/goiteens.homework pull request #40
Opened 2024-04-27 11:01 UTC by Kilim4ik

2024-05-07 14:03 UTC, marianaD4 requested changes

2024-05-07 14:03 UTC, marianaD4 commented on third semester/hw11/main.js
> +console.log(bankAccount);
ті ж самі коментарі, що і до попереднього методу

2024-05-07 14:03 UTC, marianaD4 commented on third semester/hw11/main.js
> +};
має бути методом об'єкта weather

2024-05-07 14:03 UTC, marianaD4 commented on third semester/hw11/main.js
> +  }
можна розбити на окремі if, тому що є return

2024-05-07 14:03 UTC, marianaD4 commented on third semester/hw11/main.js
> +    return false;
використовуємо скорочений синтаксис `return movie.rating > 8`

2024-05-13 15:40 UTC, marianaD4 requested changes

2024-05-13 15:40 UTC, marianaD4 commented on third semester/hw11/main.js
> +  bankAccount.balance += num;
this

2024-05-13 15:40 UTC, marianaD4 commented on third semester/hw11/main.js
> +  // this.balance += num;
https://github.com/Kilim4ik/goiteens.homework/pull/40/files#r1592536856

2024-05-13 15:40 UTC, marianaD4 commented on third semester/hw11/main.js
> +  bankAccount.balance -= num;
this

2024-05-13 15:40 UTC, marianaD4 commented on third semester/hw11/main.js
> +const isUpper0 = () => weather.temperature >= 0;
зроби як метод об'єкта weather

2024-05-13 15:40 UTC, marianaD4 commented on third semester/hw11/main.js
> +  }
якщо всі варіанти перевірии вище. тоді if останній зайвий

2024-06-25 13:57 UTC, DzividzinskaM approved these changes

2024-07-07 07:32 UTC, merged